### ISSUE TITLE
Export FBX clears my Blender undo history

### ISSUE THREAD

**Issue by mikeseese** [vespero-group/chiro-ue4#17]
When executing the Export FBX function within Chiro UE4, I lose all of my Undo History. The title bar shows that I have a `(Recovered)` blend file and my Undo History just has two entries: `Original` and `Export FBX (Chiro UE4)`. I expect the plugin to not change my prior Undo History and for the session to become "dirty" because I made the export function, rather than appearing to load a recovered save?

I tested the normal FBX export function in Blender, and it does not clear my Undo History

Blender version: v2.92.0
Chiro UE4 version: v0.1.1

**Comment by mikeseese** [comment]
Looking at the code, this behavior seems to be "as designed", and is not intended as a bug, so this is more of a feature request then.

Here, you call `snapshot_then_rollback_ctx()`: https://github.com/vespero-group/chiro-ue4/blob/c05e7ec83eedf59482dc56063738983f3e370ad9/addon/ops/fbx_export.py#L35

Which is defined here:

https://github.com/vespero-group/chiro-ue4/blob/c05e7ec83eedf59482dc56063738983f3e370ad9/addon/utils/context.py#L110-L119

It's clear that the intention is to modify the blender file and then rollback to an auto save.

Making the below modification does the same behavior while preserving the undo history.

``` diff
def snapshot_then_rollback_ctx(): 
    with temp_file_ctx() as filepath: 
        try: 
            bpy.ops.wm.save_as_mainfile(copy=True, filepath=filepath) 

            yield 

        finally: 
--            if os.path.exists(filepath): 
--                bpy.ops.wm.recover_auto_save(filepath=filepath) 
++            bpy.ops.ed.undo()

```

I can write a PR if you're interested in these changes, but I'm not sure if/how you want to change/preserve the file writing. Perhaps it's good to force an auto save before exporting so that if Blender crashes during export, an autosave right before export is available.

**Comment by mikeseese** [comment]
My proposed changes don't work 😅 I thought they did, but apparently they don't. I don't know of a fix or alternative method. I don't think this means we close this issue. I do think it's really important to not get rid of the undo history. Perhaps the armature can be duplicated, modified, and deleted, rather than edited and reverted to a save file

**Comment by dnsl48** [comment]
Hi @seesemichaelj,
Thank you for reporting the issue!
Yes, the "recovery" is a designed behaviour to revert the _breaking_ changes to the mesh and to the bones which the *Export* feature performs under the hood.
Unfortunately, that comes with the side-effect of losing all "history", because technically that's a "load" of an autosave (as you already found it in the code - `recover_auto_save`).
At this point we couldn't find a better way to "revert" the breaking changes via the existing Blender APIs, so might need to accept that as a limitation.

However, it would definitely be nice to solve that problem if there was a better way (which I don't see right now) :)


> bpy.ops.ed.undo()

That would be hard to do because the "Export" feature triggers nonconstant amount (hundreds) of small modifications which we'd have to rollback all at the same time. A potential way would be to "count" all the modifications and then invoke the required amount of "undo", but that might be really tricky and error-prone.
